### ISSUE TITLE
Remove `iroha_crypto`, `iroha_config` and `iroha_data_model` from `Cargo.toml`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha-2-docs#449]
Since we have re-exported these dependencies through `iroha_client`, if any of the documentation examples uses them like in the following `Cargo.toml` example:

```toml
[dependencies]
iroha_client = { version = "=2.0.0-pre-rc.13", path = "~/Git/iroha/client" }
iroha_data_model = { version = "=2.0.0-pre-rc.13", path = "~/Git/iroha/data_model" }
iroha_crypto = { version = "=2.0.0-pre-rc.13", path = "~/Git/iroha/crypto" }
iroha_config = { version = "=2.0.0-pre-rc.13", path = "~/Git/iroha/config" }
```

replace it with:
```toml
[dependencies]
iroha_client = { version = "=2.0.0-pre-rc.13", path = "~/Git/iroha/client" }
```

this will also require that we access these dependencies:
```rs
use iroha_config::client::Configuration;
use iroha_crypto::KeyPair;
use iroha_data_model::prelude::*;
```

through `iroha_client` like this:
```rs
use iroha_client::{
    config::Configuration,
    crypto::KeyPair,
    data_model::prelude::*,
};
```
